name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPORT_DIR: ${{ github.workspace }}/Reports/framework.html

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Install Edge WebDriver and run tests
        run: |
          # Install Microsoft Edge Driver and set up environment
          wget https://msedgedriver.azureedge.net/113.0.1774.50/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/

          # Run the tests (with increased timeout settings)
          mvn test -Dtest=tests.UserTest -DpageLoadTimeout=600000 -DuserDataDir=/tmp/edge-user-data --no-transfer-progress

      - name: Show Surefire Report Content
        run: |
          cat target/surefire-reports/*.txt

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/surefire-reports/

