name: Build and Test Java Project with Firefox

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Firefox and dependencies
      - name: Install Firefox and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox libgtk-3-0 libdbus-glib-1-2 libxt6 wget
          wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
         tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      # Install Firefox WebDriver using WebDriverManager
      - name: Install Firefox WebDriver using WebDriverManager
        run: |
          mvn dependency:copy-dependencies -Dartifact=io.github.bonigarcia:webdrivermanager:5.3.0

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      # Submit Dependency Snapshot
      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v1.0.0
        with:
          github_token: ${{ secrets.MY_PAT }}
